"""update college_details table

Revision ID: 00e4640dbaf5
Revises: c79fff0f5e20
Create Date: 2025-12-28 12:41:05.059533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '00e4640dbaf5'
down_revision: Union[str, Sequence[str], None] = 'c79fff0f5e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_details', sa.Column('degree', sa.String(length=100), nullable=True))
    op.add_column('college_details', sa.Column('branch', sa.String(length=100), nullable=True))
    op.add_column('college_details', sa.Column('fees_value', sa.String(length=100), nullable=True))
    op.add_column('college_details', sa.Column('fees_source', sa.String(length=500), nullable=True))
    op.add_column('college_details', sa.Column('fees_extracted_text', sa.String(length=1000), nullable=True))
    op.add_column('college_details', sa.Column('avg_package_value', sa.String(length=100), nullable=True))
    op.add_column('college_details', sa.Column('avg_package_source', sa.String(length=500), nullable=True))
    op.add_column('college_details', sa.Column('avg_package_extracted_text', sa.String(length=1000), nullable=True))
    op.add_column('college_details', sa.Column('highest_package_value', sa.String(length=100), nullable=True))
    op.add_column('college_details', sa.Column('highest_package_source', sa.String(length=500), nullable=True))
    op.add_column('college_details', sa.Column('highest_package_extracted_text', sa.String(length=1000), nullable=True))
    op.add_column('college_details', sa.Column('entrance_exam_value', sa.String(length=100), nullable=True))
    op.add_column('college_details', sa.Column('entrance_exam_source', sa.String(length=500), nullable=True))
    op.add_column('college_details', sa.Column('entrance_exam_extracted_text', sa.String(length=1000), nullable=True))
    op.add_column('college_details', sa.Column('cutoff_value', sa.String(length=200), nullable=True))
    op.add_column('college_details', sa.Column('cutoff_source', sa.String(length=500), nullable=True))
    op.add_column('college_details', sa.Column('cutoff_extracted_text', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_college_details_college_id'), 'college_details', ['college_id'], unique=False)
    op.drop_column('college_details', 'degrees')
    op.drop_column('college_details', 'fees')
    op.drop_column('college_details', 'avg_package')
    op.drop_column('college_details', 'last_fetched_at')
    op.drop_column('college_details', 'entrance_exam')
    op.drop_column('college_details', 'source_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_details', sa.Column('source_urls', sqlite.JSON(), nullable=True))
    op.add_column('college_details', sa.Column('entrance_exam', sa.VARCHAR(length=100), nullable=True))
    op.add_column('college_details', sa.Column('last_fetched_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('college_details', sa.Column('avg_package', sa.VARCHAR(length=100), nullable=True))
    op.add_column('college_details', sa.Column('fees', sa.VARCHAR(length=100), nullable=True))
    op.add_column('college_details', sa.Column('degrees', sqlite.JSON(), nullable=True))
    op.drop_constraint('uq_college_degree_branch', 'college_details', type_='unique')
    op.drop_index(op.f('ix_college_details_college_id'), table_name='college_details')
    op.drop_column('college_details', 'cutoff_extracted_text')
    op.drop_column('college_details', 'cutoff_source')
    op.drop_column('college_details', 'cutoff_value')
    op.drop_column('college_details', 'entrance_exam_extracted_text')
    op.drop_column('college_details', 'entrance_exam_source')
    op.drop_column('college_details', 'entrance_exam_value')
    op.drop_column('college_details', 'highest_package_extracted_text')
    op.drop_column('college_details', 'highest_package_source')
    op.drop_column('college_details', 'highest_package_value')
    op.drop_column('college_details', 'avg_package_extracted_text')
    op.drop_column('college_details', 'avg_package_source')
    op.drop_column('college_details', 'avg_package_value')
    op.drop_column('college_details', 'fees_extracted_text')
    op.drop_column('college_details', 'fees_source')
    op.drop_column('college_details', 'fees_value')
    op.drop_column('college_details', 'branch')
    op.drop_column('college_details', 'degree')
    # ### end Alembic commands ###
