"""add degrees table

Revision ID: 5cda92213c2b
Revises: 74bca6b2da04
Create Date: 2025-12-12 23:03:12.399087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cda92213c2b'
down_revision: Union[str, Sequence[str], None] = '74bca6b2da04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stream', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_degrees_id'), 'degrees', ['id'], unique=False)
    op.create_index(op.f('ix_degrees_stream'), 'degrees', ['stream'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_degrees_stream'), table_name='degrees')
    op.drop_index(op.f('ix_degrees_id'), table_name='degrees')
    op.drop_table('degrees')
    # ### end Alembic commands ###
