"""add stream column to profiles

Revision ID: 6e81cf32d6a0
Revises: 5b7c357e7c10
Create Date: 2025-12-25 12:13:43.085912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e81cf32d6a0'
down_revision: Union[str, Sequence[str], None] = '5b7c357e7c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_level', sa.String(), nullable=False),
    sa.Column('roadmap_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_id'), 'roadmap', ['id'], unique=False)
    op.create_table('roadmap_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('reference_table', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_step_id'), 'roadmap_step', ['id'], unique=False)
    op.add_column('profiles', sa.Column('stream', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'stream')
    op.drop_index(op.f('ix_roadmap_step_id'), table_name='roadmap_step')
    op.drop_table('roadmap_step')
    op.drop_index(op.f('ix_roadmap_id'), table_name='roadmap')
    op.drop_table('roadmap')
    # ### end Alembic commands ###
