"""add college details cache

Revision ID: 6ff2f7c3266b
Revises: 1b3afcaeadbe
Create Date: 2025-12-27 15:27:26.707166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff2f7c3266b'
down_revision: Union[str, Sequence[str], None] = '1b3afcaeadbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('degrees', sa.JSON(), nullable=True),
    sa.Column('entrance_exam', sa.String(length=100), nullable=True),
    sa.Column('fees', sa.String(length=100), nullable=True),
    sa.Column('avg_package', sa.String(length=100), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id')
    )
    op.create_index(op.f('ix_college_enrichments_id'), 'college_enrichments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_college_enrichments_id'), table_name='college_enrichments')
    op.drop_table('college_enrichments')
    # ### end Alembic commands ###
