"""add_backward_planner_tables

Revision ID: e749fa088195
Revises: 6ae5d11af17a
Create Date: 2026-01-20 12:06:15.120719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e749fa088195'
down_revision: Union[str, Sequence[str], None] = '6ae5d11af17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('career_description', sa.Text(), nullable=True),
    sa.Column('required_education', sa.JSON(), nullable=True),
    sa.Column('entrance_exams', sa.JSON(), nullable=True),
    sa.Column('stream_recommendation', sa.JSON(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('projects_to_build', sa.JSON(), nullable=True),
    sa.Column('internships', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('top_colleges', sa.JSON(), nullable=True),
    sa.Column('career_prospects', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_templates_career_name'), 'career_templates', ['career_name'], unique=True)
    op.create_index(op.f('ix_career_templates_category'), 'career_templates', ['category'], unique=False)
    op.create_index(op.f('ix_career_templates_id'), 'career_templates', ['id'], unique=False)
    op.create_table('backward_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('career_goal_input', sa.String(length=500), nullable=False),
    sa.Column('normalized_career', sa.String(length=200), nullable=False),
    sa.Column('career_category', sa.String(length=100), nullable=True),
    sa.Column('career_description', sa.Text(), nullable=True),
    sa.Column('required_education', sa.JSON(), nullable=True),
    sa.Column('entrance_exams', sa.JSON(), nullable=True),
    sa.Column('stream_recommendation', sa.JSON(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('projects_to_build', sa.JSON(), nullable=True),
    sa.Column('internships', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('top_colleges', sa.JSON(), nullable=True),
    sa.Column('career_prospects', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backward_roadmaps_id'), 'backward_roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_backward_roadmaps_normalized_career'), 'backward_roadmaps', ['normalized_career'], unique=False)
    op.create_index(op.f('ix_backward_roadmaps_user_id'), 'backward_roadmaps', ['user_id'], unique=False)
    op.create_index(op.f('ix_college_details_college_id'), 'college_details', ['college_id'], unique=False)
    op.create_index(op.f('ix_college_details_id'), 'college_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_college_details_id'), table_name='college_details')
    op.drop_index(op.f('ix_college_details_college_id'), table_name='college_details')
    op.drop_index(op.f('ix_backward_roadmaps_user_id'), table_name='backward_roadmaps')
    op.drop_index(op.f('ix_backward_roadmaps_normalized_career'), table_name='backward_roadmaps')
    op.drop_index(op.f('ix_backward_roadmaps_id'), table_name='backward_roadmaps')
    op.drop_table('backward_roadmaps')
    op.drop_index(op.f('ix_career_templates_id'), table_name='career_templates')
    op.drop_index(op.f('ix_career_templates_category'), table_name='career_templates')
    op.drop_index(op.f('ix_career_templates_career_name'), table_name='career_templates')
    op.drop_table('career_templates')
    # ### end Alembic commands ###
